### ISSUE TITLE
Impliment an easy way to copy Sigil 1's choices to sigil 2

### ISSUE THREAD

**Issue by Prezombie** [discretize/discretize-gear-optimizer#503]
An easy way to do it would be, If sigil 2 menu is empty, it acts like a copy of Sigil 1's list. Good for condi builds with a bunch of options.

A more complex way, have the selected sigils in the other menu highlighted, and a button to "merge lists"

**Comment by marcustyphoon** [comment]
Excellent idea! I would probably lean away from the first idea just because there are so many current templates with blank extras slots that really just mean "we don't have a good simulation for the sigils that are in this slot in the benchmark" (although I could convert those to "empty" items, so it's not impossible to do that too.
